### ISSUE TITLE
Team Meeting 2016-12-16

### ISSUE THREAD

**Issue by lig** [stonicio/stonic#5]
> 2016-12-16 13:30:00 GMT

# Meeting Agenda

- [ ] Discuss high level plans
- [ ] Milestone 0.1 grooming

**Comment by khatribharat** [comment]
Is this meeting open invitation or invite only?

**Comment by lig** [comment]
@khatribharat we will use Hangouts or Zoom. Will try to share live stream.

**Comment by lig** [comment]
Meeting postponed. New time is near 16:00 GMT

**Comment by lig** [comment]
New time is 13:30 GMT

**Comment by lig** [comment]
Sorry guy, I had a bad connection and couldn't stream the meeting.

Agreed to go ahead writing https://github.com/stonicio/papers

Discussed a number of ideas on architecture.

Agreed that we will try to support existing Ansible playbooks as much as possible and that we need a static playbook analyzer that will catch any incompatibilities.

Further steps:

- Write Papers on Inventory and Context Manager @lig
- Review Papers @alexclear and community
- Write some code :) @lig @alexclear
